const projects=[
{title:'Brand Book GxSoul/KRTY',description:'Айдентика и руководство по визуальному стилю.',category:'identity',label:'01 / BRAND IDENTITY',tags:['Айдентика','Брендбук'],image:'brandbook.jpg',url:'https://www.behance.net/gallery/246885793/Brand-Book-GxSoulKRTY'},
{title:'XFit Rebranding',description:'Концепция ребрендинга фитнес-сети · учебный проект.',category:'identity',label:'02 / REBRANDING',tags:['Ребрендинг','Учебный проект'],image:'xfit.jpg',url:'https://www.behance.net/gallery/249997653/XFit-Rebranding'},
{title:'Portfolio Website',description:'Сайт-портфолио · учебный проект.',category:'digital',label:'03 / DIGITAL DESIGN',tags:['UI/UX','Учебный проект'],image:'portfolio.jpg',url:'https://www.behance.net/gallery/251160601/Portfolio-Website'},
{title:'Journal',description:'Журнальная вёрстка и редакционный дизайн.',category:'editorial',label:'04 / EDITORIAL DESIGN',tags:['Редакционный дизайн','Вёрстка'],image:'journal.jpg',url:'https://www.behance.net/gallery/229126569/Journal-Full-fledged-layout-of-the-magazine'}];
const isEnglish=document.documentElement.lang==='en';
const copy=isEnglish?{open:'Open menu',close:'Close menu',view:'View project ↗'}:{open:'Открыть меню',close:'Закрыть меню',view:'Смотреть проект ↗'};
if(isEnglish){const descriptions=['Brand identity and brand guidelines.','Fitness brand rebranding concept · college project.','Portfolio website · college project.','Magazine layout and editorial design.'];const tags=[['Visual identity','Brand guidelines'],['Rebranding','College project'],['UI/UX','College project'],['Editorial design','Layout']];projects.forEach((p,i)=>{p.description=descriptions[i];p.tags=tags[i];});}
const asset=name=>'assets/profile/'+name;
function element(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text)el.textContent=text;return el;}
function picture(name,alt){const img=element('img');img.src=asset(name);img.alt=alt;img.loading='lazy';return img;}
projects.forEach((p,index)=>{const card=element('button','project');card.dataset.category=p.category;card.dataset.project=index;const cover=element('div','cover');cover.append(picture(p.image,p.title),element('span','case-overlay',copy.view));const meta=element('div','project-meta'),text=element('div');text.append(element('span','project-number',p.label),element('h3','',p.title),element('p','',p.description));meta.append(text,element('span','round-arrow','↗'));card.append(cover,meta);document.querySelector('#project-grid').append(card);});
['Illustrator','Photoshop','Figma','InDesign','Lightroom'].forEach(name=>{const div=element('div');const title=name==='Figma'?name:'Adobe '+name;div.append(picture('tool-'+name.toLowerCase()+'-transparent.png',title),element('h3','',name),element('p','',title));document.querySelector('#tool-grid').append(div);});
const socials=[['social-behance-bilingual.png','Behance — Портфолио / Portfolio','https://www.behance.net/tuumiyurmirazh'],['social-telegram-bilingual.png','Telegram — Связь / Contact','https://t.me/designeramigo'],['social-email-bilingual.png','Email / Почта — Написать / Write to me','mailto:xghostxsoulx@gmail.com'],['social-work-matched.png','Telegram — канал с работами / Work channel','https://t.me/soulamigo'],['social-instagram-matched.png','Instagram — @xgxsoul_kartaviyx','https://www.instagram.com/xgxsoul_kartaviyx/'],['social-tiktok-matched.png','TikTok — фотографии / Photography','https://www.tiktok.com/@xkartaviyx_']];
socials.forEach(([file,label,url],i)=>{if(isEnglish)label=['Behance — Portfolio','Telegram — Contact','Email — Write to me','Telegram — Work channel','Instagram — @xgxsoul_kartaviyx','TikTok — Photography'][i];const a=element('a');a.href=url;if(url.startsWith('https:')){a.target='_blank';a.rel='noopener noreferrer';}a.append(picture(file,label));document.querySelector('#social-grid').append(a);});
const menu=document.querySelector('.menu'),nav=document.querySelector('.header nav');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label',copy.open);}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?copy.close:copy.open);});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{const selected=b===button;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});document.querySelectorAll('[data-project]').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter);}));
const dialog=document.querySelector('#project-dialog');document.querySelectorAll('[data-project]').forEach(card=>card.addEventListener('click',()=>{const p=projects[Number(card.dataset.project)];dialog.querySelector('h2').textContent=p.title;dialog.querySelector('.dialog-description').textContent=p.description;const img=dialog.querySelector('.dialog-image');img.src=asset(p.image);img.alt=p.title;dialog.querySelector('.dialog-link').href=p.url;dialog.querySelector('.dialog-details').replaceChildren(...p.tags.map(tag=>element('span','',tag)));dialog.showModal();}));document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
const activeObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)nav.querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id));});},{rootMargin:'-10% 0px -65% 0px'});document.querySelectorAll('main section[id]').forEach(s=>activeObserver.observe(s));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const revealObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');revealObserver.unobserve(e.target);}});},{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('will-reveal');revealObserver.observe(el);});if(matchMedia('(hover: hover) and (pointer: fine)').matches){document.querySelectorAll('.project').forEach(card=>{let frame;card.addEventListener('pointermove',e=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.setProperty('--tilt-x',(0.5-y)*4+'deg');card.style.setProperty('--tilt-y',(x-0.5)*4+'deg');card.style.setProperty('--shine-x',x*100+'%');card.style.setProperty('--shine-y',y*100+'%');});});card.addEventListener('pointerleave',()=>{cancelAnimationFrame(frame);card.style.setProperty('--tilt-x','0deg');card.style.setProperty('--tilt-y','0deg');});});}}

// Keep the current section when switching languages.
document.querySelectorAll('.language-switch a').forEach(a=>a.addEventListener('click',()=>{a.href=a.getAttribute('href').split('#')[0]+location.hash;}));
